### ISSUE TITLE
[SUGESTAO] Adicionar alguma logica de negocio

### ISSUE THREAD

**Issue by rrfaria** [waldemarnt/building-testable-apis-with-nodejs-code#29]
Oi Waldemar, achei muito boa sua iniciativa de disponibilizar o projeto pra galera. 

Queria sugerir algo:

- adicionar algumas logicas de negócios diferente para cada item, para mostrar qual a melhor forma de tratar os business exceptions. Por exemplo:
   - se o produto não tem estoque retorna um erro tratado
   - se o produto está faltando alguma informação retorna um erro
- Retornar error codes que o Frontend possa tratar com i18n

```json
{
    "success": false,
    "errors": [
    {
      "code": "those.skus.are.not.found",
      "message": "There are no stock available for those SKUS",
      "data": ["D4324-00192-1923", "D4324-00192-4922", "D4324-00192-9876"]
    },
    {
      "code": "coupon.code.expired",
      "message": "This coupon is not available",
      "data": "JS10"
    }
  ]
}
```

Meus parabéns pelo projeto é uma ótima ajuda para a comunidade open source.

**Comment by waldemarnt** [comment]
@rrfaria gostei da ideia, tens alguma ideia de logica de negocio? Vou pensar aqui e te retorno

**Comment by waldemarnt** [comment]
@rrfaria da uma olhada no meu novo curso https://www.youtube.com/watch?v=W2ld5xRS3cY&list=PLz_YTBuxtxt6_Zf1h-qzNsvVt46H8ziKh tem bastante logica de negocio!
